name: Android

on:
  push:
    branches: [ "main", "CI" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    
concurrency:
  group: "build_android"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Install Android NDK
      uses: actions/setup-ndk@v1
      with:
        ndk-version: r28

    - name: Install Android SDK
      uses: actions/setup-android-sdk@v1
      with:
        sdk-version: '30'
        api-level: 30

    - name: Install Android Emulator
      run: |
        echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --licenses
        $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-30;google_apis;x86_64"
        $ANDROID_HOME/tools/emulator -list-avds || $ANDROID_HOME/tools/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force
        nohup $ANDROID_HOME/tools/emulator -avd test -no-window -no-audio -gpu off -verbose &
        adb wait-for-device

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: > 
        cmake
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake 
        -DANDROID_ABI=arm64-v8a
        -DANDROID_PLATFORM=android-30
        -DCMAKE_CXX_FLAGS='-w -O2 -landroid -llog'
        -DHEPH_BUILD_TESTS=ON
        -S .
        -B build/

    - name: Build
      working-directory: ${{github.workspace}}
      run: cmake --build build

    - name: Run Tests
      working-directory: ${{github.workspace}}
      run: >
        adb push build/tests/HephTests /data/local/tmp/
        adb shell chmod 755 /data/local/tmp/HephTests
        adb shell /data/local/tmp/HephTests