name: Android

on:
  push:
  pull_request:

  workflow_dispatch:
    
concurrency:
  group: "build_android"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Install Android NDK
      run: |
        mkdir -p $HOME/Android/Sdk/ndk
        cd $HOME/Android/Sdk/ndk
        curl -L https://dl.google.com/android/repository/android-ndk-r28-linux.zip -o android-ndk.zip
        unzip android-ndk.zip
        rm android-ndk.zip

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: > 
        cmake
        -DCMAKE_TOOLCHAIN_FILE=$HOME/Android/Sdk/ndk/android-ndk-r28/build/cmake/android.toolchain.cmake 
        -DANDROID_ABI=arm64-v8a
        -DANDROID_PLATFORM=android-30
        -DCMAKE_CXX_FLAGS='-w -O2 -landroid -llog'
        -DHEPH_BUILD_TESTS=ON
        -S .
        -B build/

    - name: Build
      working-directory: ${{github.workspace}}
      run: cmake --build build